config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('groomings.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groomings/urls.py
from django.urls import path
from . import views

app_name = 'groomings'
urlpatterns = [
    path(r'', views.top, name = 'top'), # タイムライン
    path(r'search/', views.search, name='search'), # 検索ページ
    path(r'login/', views.user_login, name = 'login'), # ログイン画面
    path(r'logout/', views.user_logout, name = 'logout'), #ログアウト用
    path(r'signup/', views.user_signup, name = 'signup'), # ユーザー登録画面
    path(r'user/<int:user_id>/', views.user, name = 'user'), # ユーザー個人ページ
    path(r'user/<int:user_id>/favo', views.user_favo, name='user_favo'), # ユーザーのお気に入り投稿ページ
    path(r'edit_user/', views.edit_user, name='edit_user'), # ユーザー情報編集ページ
    path(r'change_password/', views.change_password, name='change_password'), # パスワードの変更ページ
    path(r'post/', views.create_post, name='create_post'), # post投稿ページ
    path(r'ranking/', views.ranking, name='ranking'), # ランキング用のページ
    path(r'post/<int:post_id>/', views.post_detail, name='post_detail'), # 投稿詳細ページ(<int:post_id>必要)
    path(r'post/edit/<int:post_id>/', views.post_edit, name='post_edit'), # 投稿編集ページ
    path(r'post/delete/<int:post_id>/', views.post_delete, name='post_delete'), # 投稿削除
    path(r'create_question/<int:user_id>/', views.create_question, name='create_question'), # 匿名質問をするためのページ(<int:user_id>(質問する相手のid)必要)
    path(r'anyms/', views.anyms, name='anyms'), # 匿名質問一覧ページ(自分にきた質問と自分がした質問を一覧表示)
    path(r'question/<int:question_id>/', views.question_detail, name='question_detail'), # 秘密質問の詳細ページ(<int:question_id>必要)
    path(r'follow/<int:user_id>/', views.follow, name='follow'), # フォロー用のurl
    path(r'unfollow/<int:user_id>/', views.unfollow, name='unfollow'), # フォロー解除用のurl
    path(r'followee/<int:user_id>/', views.followee, name='followee'), # フォローしてるユーザー一覧ページ
    path(r'follower/<int:user_id>/', views.follower, name='follower'), # フォロワーの一覧ページ
    path(r'favorite/<int:post_id>/', views.favorite, name='favorite'), # 投稿へのいいねあるいはいいねの取り消し用url
    path(r'favo_comme/<int:comment_id>/', views.favo_comme, name='favo_comme'), # コメントへのグッドあるいはグッドの取り消し用url
    path(r'bad_comme/<int:comment_id>/', views.bad_comme, name='bad_comme'), # コメントへのバッドあるいはバッドの取り消しようurl
]

groomings/forms.py
from django import forms
from .models import Comment, Question, Post, Reply, User, Tag
from django.core.exceptions import ValidationError
from django.forms.widgets import PasswordInput
from django.contrib.auth.password_validation import validate_password


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class PostForm(BaseForm):
    image1 = forms.FileField(required=False)
    image2 = forms.FileField(required=False)
    image3 = forms.FileField(required=False)
    category = forms.ChoiceField(
        choices = (
            ('none_category', 'カテゴリーなし'),
            ('skincare', 'スキンケア'),
            ('make', 'メイク'),
            ('hair', 'ヘアー'),
            ('fashion', '服装'),
            ('others', 'その他')
        ),
    )

    class Meta:
        model = Post
        exclude = ['user', 'favorite', 'created_at']
        labels = {
            'title': 'タイトル',
            'image1': '画像1',
            'image2': '画像2',
            'image3': '画像3',
            'text': '説明',
            'category': 'カテゴリー'
        }

class CommentForm(BaseForm):
    class Meta:
        model = Comment
        fields =('text',)

class QuestionForm(BaseForm):
    image1 = forms.FileField(required=False)
    image2 = forms.FileField(required=False)
    image3 = forms.FileField(required=False)

    class Meta:
        model = Question
        exclude = ['good_question', 'good_answer', 'created_at', 'giver', 'recipient', 'to_giver_point', 'to_recipient_point', 'is_active']
        label = {
            'title': 'タイトル',
            'text': '本文',
            'image1': '画像1',
            'image2': '画像2',
            'image3': '画像3',
            'give_point': '付与するポイント',
        }

class ReplyForm(BaseForm):
    image = forms.FileField(required=False)
    
    class Meta:
        model = Reply
        fields = ('text', 'image')

# ユーザー追加用のフォーム
class UserAddForm(BaseForm):
    password = forms.CharField(label='password', widget=PasswordInput)
    confirm_password = forms.CharField(label='Password再入力', widget=PasswordInput)
    image = forms.FileField(required=False)
    class Meta:
        model = User
        fields = ['username', 'image', 'email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise ValidationError('パスワードが一致しません')

    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(user.password)
        user.save()
        return user


class UserEditForm(BaseForm):
    username = forms.CharField(label='ユーザー名')
    email = forms.EmailField(label='メールアドレス')
    image = forms.FileField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'image')

class PasswordChangeForm(BaseForm):
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('password',)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが異なります')

    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

class LoginForm(forms.Form):
    email = forms.EmailField(label='メールアドレス', max_length=255)
    password = forms.CharField(label='パスワード', widget=PasswordInput)

class TagForm(BaseForm):
    class Meta:
        model = Tag
        fields = ('name',)

config/groomings/views.py
from django.shortcuts import render

# Create your views here.
def top(request):
    return render(request, 'groomings/top.html')

groomings/views.py
from django.db.models.fields import EmailField
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from groomings.models import User, Post, Comment, Question, Reply, Tag, Notify
from django.contrib import messages
from django.db.models import Count
from django.db.models import Q
from datetime import datetime, timedelta
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.views.generic import TemplateView

def top(request):
    """トップ画面"""
    if request.user.is_authenticated: # ログインしていたらフォロー中ユーザーの投稿を表示
        users = request.user.follow.all()
        posts = Post.objects.filter(Q(user__in=users) | Q(user=request.user)).order_by('-created_at')
    else:
        posts = Post.objects.order_by('-created_at')
    return render(request, 'groomings/top.html', context={"posts": posts})

def search(request):
    posts = Post.objects.order_by('-created_at')
    all_tags = Tag.objects.all()
    check_tag_ids = []
    if request.GET.get('button') == "検索する":
        q_word = request.GET.get('query')
        if request.GET.get('category') == "all" :
            posts = posts.filter(Q(title__icontains=q_word) | Q(text__icontains=q_word)).order_by('-created_at')
        else:
            posts = posts.filter(Q(title__icontains=q_word) | Q(text__icontains=q_word), category=request.GET.get('category')).order_by('-created_at')
        check_tag_ids = request.GET.getlist("tag")
        check_tag_ids = [int(i) for i in check_tag_ids]
        for tag_id in check_tag_ids:
                posts = posts.filter(having_tags=tag_id).order_by('-created_at')

    return render(request, 'groomings/search.html', context={"posts": posts, "tags": all_tags, "check_tag_ids": check_tag_ids})

def user_login(request):
    """ログイン画面"""
    login_form = forms.LoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if user:
            if user.is_active:
                login(request, user) # ログイン
                messages.success(request, 'ログインしました')
                return redirect('groomings:top')
        messages.warning(request, 'ログインできませんでした')
    return render(request, 'groomings/login.html', context={
        'login_form': login_form
    })

@login_required
def user_logout(request):
    logout(request)
    messages.success(request, 'ログアウトしました')
    return redirect('groomings:login')

def user_signup(request):
    """サインアップ画面"""
    form = forms.UserAddForm()
    if request.method == 'POST':
        form = forms.UserAddForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, 'ユーザーを登録しました')
                return redirect('groomings:login')
            except ValidationError as e:
                form.add_error('password', e) # formのパスワードの部分にエラー内容を追加
        messages.warning(request, '再入力してください')
    return render(request, 'groomings/signup.html', context={
        'form': form,
    })

def user(request, user_id):
    """ユーザーページ"""
    user = User.objects.get(pk=user_id)
    posts = user.user_post.all()
    eval_as_giver = user.user_give_question.filter(is_active=False).order_by('-created_at')
    eval_as_recipient = user.user_receive_question.filter(is_active=False).order_by('-created_at')
    if request.user.is_authenticated:
        my_follows = request.user.follow.all()
        notifys = Notify.objects.filter(user=request.user).order_by('-created_at')
        return render(request, 'groomings/user.html', context={
            "page_owner": user, "my_follows": my_follows, "posts": posts, "notifys": notifys, "eval_as_giver": eval_as_giver, "eval_as_recipient": eval_as_recipient
            })
    else:
        return render(request, 'groomings/user.html', context={
            "page_owner": user, "posts": posts, "eval_as_giver": eval_as_giver, "eval_as_recipient": eval_as_recipient
            })

@login_required
def user_favo(request, user_id):
    """ユーザーのお気に入りした投稿一覧ページ"""
    user = User.objects.get(pk=user_id)
    my_follows = request.user.follow.all()
    favo_posts = user.user_favo_post.all()
    notifys = Notify.objects.filter(user=request.user).order_by('-created_at')
    eval_as_giver = user.user_give_question.filter(is_active=False).order_by('-created_at')
    eval_as_recipient = user.user_receive_question.filter(is_active=False).order_by('-created_at')
    return render(request, 'groomings/user_favo.html', context={
        "page_owner": user, "my_follows": my_follows, 'favo_posts': favo_posts, "notifys": notifys, "eval_as_giver": eval_as_giver, "eval_as_recipient": eval_as_recipient
        })

@login_required
def edit_user(request):
    """ユーザー情報編集ページ"""
    edit_user_form = forms.UserEditForm(request.POST or None, request.FILES or None, instance=request.user)
    if edit_user_form.is_valid():
        edit_user_form.save()
        messages.success(request, 'ユーザー情報を更新しました')
    return render(request, 'groomings/edit_user.html', context={"edit_user_form": edit_user_form})

@login_required
def change_password(request):
    """ユーザーパスワード編集ページ"""
    password_change_form = forms.PasswordChangeForm(request.POST or None, instance=request.user)
    if password_change_form.is_valid():
        try:
            password_change_form.save()
            messages.success(request, 'パスワードを変更しました')
            update_session_auth_hash(request, request.user)
        except ValidationError as e:
            password_change_form.add_error('password', e)
    return render(request, 'groomings/change_password.html', context={
        'password_change_form': password_change_form
        })

@login_required
def create_post(request): # user_id)
    """投稿ページ"""
    form = forms.PostForm(request.POST or None, request.FILES or None)
    tag_form = forms.TagForm(request.POST or None)
    tags = Tag.objects.all()

    if tag_form.is_valid():
        tag_form.save()
        return redirect('groomings:create_post')

    if form.is_valid(): # バリデーションがOKなら保存
        form.instance.user = request.user
        toukou = form.save()
        check_tag_ids = request.POST.getlist("tag")
        for tag_id in check_tag_ids:
            Tag.objects.get(pk=tag_id).post.add(toukou)

        messages.info(request, f'投稿しました。ユーザー:{toukou.user} タイトル:{toukou.title} pk:{toukou.pk}')
        return redirect('groomings:top')
    return render(request, 'groomings/create_post.html', context={"form": form, "tag_form": tag_form, "tags": tags})

def ranking(request):
    """ランキング用のページ"""
    points = User.objects.order_by('-point')[:10]
    follower = User.objects.annotate(num_follower=Count('follower')).order_by('-num_follower')[:10]
    num_que = User.objects.annotate(num_que=Count('user_receive_question')).order_by('-num_que')[:10]
    
    post_orderby_favo = Post.objects.annotate(num_favo=Count('favorite')).order_by('-num_favo')[:10]
    return render(request, 'groomings/ranking.html',context={"points": points, "followers": follower, "num_que": num_que, "goods": post_orderby_favo}) # , 'id': user_id})

# @login_required
def post_detail(request, post_id):
    """投稿詳細ページ"""
    post = Post.objects.get(pk=post_id)
    comme_form = forms.CommentForm(request.POST or None)
    if request.user.is_authenticated:
        if comme_form.is_valid():
            if good_bad(request.user) > -10: # 1週間以内のコメントに対するbadがgood+10を上回るとコメできない
                comme_form.instance.user = request.user
                comme_form.instance.post = post
                comme_form.save()
                messages.success(request, 'コメントしました')
                return redirect('groomings:top')
            else:
                messages.warning(request, '週間bad数がgood数+10以上だとコメできません')
        unvisited_comme_notifys = Notify.objects.filter(kind="comment", notify_id=post_id, user=request.user, is_visited=False)
        for notify in unvisited_comme_notifys: # このポストについたコメントの通知をvisitedにする
            notify.is_visited = True
            notify.save()
    comments = post.post_comment.all()
    return render(request, 'groomings/post_detail.html', context={"post": post, "form": comme_form, "comments": comments})

def good_bad(user):
    my_commes = user.user_comment.all()
    week_commes = my_commes.filter(created_at__gte = datetime.now() - timedelta(weeks=1))
    num_good = 0
    num_bad = 0
    for comme in week_commes:
        num_good += comme.favorite.count()
        num_bad += comme.bad.count()
    return num_good - num_bad

@login_required
def post_edit(request, post_id):
    """投稿編集ページ"""
    post = request.user.user_post.all().filter(pk=post_id).first()
    if not post:
        return redirect('groomings:top')
    edit_post_form = forms.PostForm(request.POST or None, request.FILES or None, instance=post)
    tags = Tag.objects.all()
    if edit_post_form.is_valid():
        toukou = edit_post_form.save()
        check_tag_ids = request.POST.getlist("tag")
        toukou.having_tags.set(check_tag_ids)
        messages.success(request, '投稿を更新しました')
    return render(request, 'groomings/edit_post.html', context={"edit_post_form": edit_post_form, "tags": tags, "post": post})

@login_required
def post_delete(request, post_id):
    """投稿削除"""
    post = request.user.user_post.all().filter(pk=post_id).first()
    if not post:
        return redirect('groomings:top')
    post.delete()
    notifys = Notify.objects.filter(kind="comment", notify_id=post_id)
    for notify in notifys:
        notify.delete()

groomings/templates/groomings/base.html
<!-- これは親htmlです -->
{% load static %}<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <!-- ナビゲーションバー -->
        <header class="mb-4">
            <nav class="navbar navbar-expand-sm navbar-light bg-light">
                <!-- ホームへ戻るリンク。ブランドロゴなどを置く。 -->
                <a href="{% url 'groomings:top' %}" class="navbar-brand"><img src="{% static 'static_image/logo.svg' %}" height="30px"></a>

                <!-- 横幅が狭いときに出るハンバーガーボタン -->
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- メニュー項目 -->
                <div class="collapse navbar-collapse" id="nav-bar">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a href="{% url 'groomings:ranking' %}" class="nav-link"><i class="fas fa-trophy"></i> ランキング</a></li>
                        <li class="nav-item"><a href="{% url 'groomings:search' %}" class="nav-link"><i class="fas fa-search"></i> 検索</a></li>
                        <li class="nav-item dropdown">
                            {% if request.user.is_authenticated %}
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-user-tie"></i> {{ request.user.username }}</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'groomings:user' request.user.id %}"><i class="fas fa-user-tie"></i> マイページ</a>
                                <a class="dropdown-item" href="{% url 'groomings:create_post' %}"><i class="fas fa-plus"></i> 投稿する</a>
                                <a class="dropdown-item" href="{% url 'groomings:edit_user' %}"><i class="fas fa-user-edit"></i> ユーザー情報変更</a>
                                <a class="dropdown-item" href="{% url 'groomings:change_password' %}"><i class="fab fa-expeditedssl"></i> パスワード変更</a>
                                <a class="dropdown-item" href="{% url 'groomings:logout' %}"><i class="fas fa-sign-out-alt"></i> ログアウト</a>
                            </div>
                            {% else %}
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-user-tie"></i> 会員機能</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'groomings:login' %}"><i class="fas fa-sign-in-alt"></i> ログイン</a>
                                <a class="dropdown-item" href="{% url 'groomings:signup' %}"><i class="fas fa-user-plus"></i> 新規登録</a>
                            </div>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container">
            <!-- messageの表示 -->
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message.message }}</div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    </body>
</html>

groomings/templates/groomings/user.html
{% extends "groomings/_user.html" %} <!-- _user.html(親)の継承 -->
{% load static %}
{% load tag_event %}

{% block posts %}
  <!-- postsの中身 -->
  <ul class="nav nav-tabs">
    <li class="nav-item"><a href="{% url 'groomings:user' page_owner.id %}" class="nav-link active">投稿<span class="badge badge-info">{{ page_owner | count_my_post }}</span></a></li>
    <li class="nav-item"><a href="{% url 'groomings:followee' page_owner.id %}" class="nav-link">フォロー<span class="badge badge-info">{{ page_owner | count_follow }}</span></a></li>
    <li class="nav-item"><a href="{% url 'groomings:follower' page_owner.id %}" class="nav-link">フォロワー<span class="badge badge-info">{{ page_owner | count_follower }}</span></a></li>
    <li class="nav-item"><a href="{% url 'groomings:user_favo' page_owner.id %}" class="nav-link">お気に入り<span class="badge badge-info">{{ page_owner | count_my_favo }}</span></a></li>
  </ul>
  
  <ul class="list-unstyled">
    {% for post in posts %}
      <li class="media mb-3 post">
          {% if post.user.image %}
          <img src="{{ post.user.image.url }}" width="40px">
          {% else %}
          <img src="{% static 'static_image/default.png' %}" width="40px">
          {% endif %}
          <div class="media-body">
              <a href="{% url 'groomings:post_detail' post.id %}">{{ post.title }}</a>
              <a href="{% url 'groomings:user' post.user.id %}">＠{{ post.user.username }}</a>
              <span class="text-muted">{{ post.created_at }}</span><br>
              {% for tag in post.having_tags.all %}
              <span class="badge badge-primary">{{ tag.name }}</span>
              {% endfor %}
              <div>
                  {{ post.text }}
              </div>
              <div class="post_image">
                  {% if post.image1 %}
                  <img src="{{ post.image1.url }}" alt="" width="100px">
                  {% endif %}
                  {% if post.image2 %}
                  <img src="{{ post.image2.url }}" alt="" width="100px">
                  {% endif %}
                  {% if post.image3 %}
                  <img src="{{ post.image3.url }}" alt="" width="100px">
                  {% endif %}
              </div>
              {% if post.user == request.user %}
              <a href="{% url 'groomings:post_edit' post.id %}"><i class="fas fa-edit"></i></a>
              <a href="{% url 'groomings:post_delete' post.id %}"><i class="fas fa-trash-alt"></i></a>
              {% endif %}
          </div>
      </li>
      {% if request.user.is_authenticated %}
          {% if request.user in post.favorite.all %}
          <a href="{% url 'groomings:favorite' post.id %}"><i class="fas fa-heart"></i><span class="badge badge-light">{{ post | count_favo }}</span></a>
          {% else %}
          <a href="{% url 'groomings:favorite' post.id %}"><i class="far fa-heart"></i><span class="badge badge-light">{{ post | count_favo }}</span></a>
          {% endif %}
      {% endif %}
      {% if request.user.is_authenticated %}
          <a href = "{% url 'groomings:post_detail' post.id %}#comment"><i class="far fa-comments"></i><span class="badge badge-light">{{ post.post_comment.count }}</span></a>
      {% endif %}
      <hr>
    {% endfor %}
  </ul>
{% endblock %}
  

groomings/templates/groomings/user_favo.html
{% extends "groomings/_user.html" %} <!-- _user.html(親)の継承 -->
{% load static %}
{% load tag_event %}

{% block posts %}
  <!-- postsの中身 -->
  <ul class="nav nav-tabs">
    <li class="nav-item"><a href="{% url 'groomings:user' page_owner.id %}" class="nav-link">投稿<span class="badge badge-info">{{ page_owner | count_my_post }}</span></a></li>
    <li class="nav-item"><a href="{% url 'groomings:followee' page_owner.id %}" class="nav-link">フォロー<span class="badge badge-info">{{ page_owner | count_follow }}</span></a></li>
    <li class="nav-item"><a href="{% url 'groomings:follower' page_owner.id %}" class="nav-link">フォロワー<span class="badge badge-info">{{ page_owner | count_follower }}</span></a></li>
    <li class="nav-item"><a href="{% url 'groomings:user_favo' page_owner.id %}" class="nav-link active">お気に入り<span class="badge badge-info">{{ page_owner | count_my_favo }}</span></a></li>
  </ul>

  <ul class="list-unstyled">
    {% for post in favo_posts %}
      <li class="media mb-3 post">
          {% if post.user.image %}
          <img src="{{ post.user.image.url }}" width="40px">
          {% else %}
          <img src="{% static 'static_image/default.png' %}" width="40px">
          {% endif %}
          <div class="media-body">
              <a href="{% url 'groomings:post_detail' post.id %}">{{ post.title }}</a>
              <a href="{% url 'groomings:user' post.user.id %}">＠{{ post.user.username }}</a>
              <span class="text-muted">{{ post.created_at }}</span><br>
              {% for tag in post.having_tags.all %}
              <span class="badge badge-primary">{{ tag.name }}</span>
              {% endfor %}
              <div>
                  {{ post.text }}
              </div>
              <div class="post_image">
                  {% if post.image1 %}
                  <img src="{{ post.image1.url }}" alt="" width="100px">
                  {% endif %}
                  {% if post.image2 %}
                  <img src="{{ post.image2.url }}" alt="" width="100px">
                  {% endif %}
                  {% if post.image3 %}
                  <img src="{{ post.image3.url }}" alt="" width="100px">
                  {% endif %}
              </div>
              {% if post.user == request.user %}
              <a href="{% url 'groomings:post_edit' post.id %}"><i class="fas fa-edit"></i></a>
              <a href="{% url 'groomings:post_delete' post.id %}"><i class="fas fa-trash-alt"></i></a>
              {% endif %}
          </div>
      </li>
      {% if request.user.is_authenticated %}
          {% if request.user in post.favorite.all %}
          <a href="{% url 'groomings:favorite' post.id %}"><i class="fas fa-heart"></i><span class="badge badge-light">{{ post | count_favo }}</span></a>
          {% else %}
          <a href="{% url 'groomings:favorite' post.id %}"><i class="far fa-heart"></i><span class="badge badge-light">{{ post | count_favo }}</span></a>
          {% endif %}
      {% endif %}
      {% if request.user.is_authenticated %}
          <a href = "{% url 'groomings:post_detail' post.id %}#comment"><i class="far fa-comments"></i><span class="badge badge-light">{{ post.post_comment.count }}</span></a>
      {% endif %}
      <hr>
    {% endfor %}
  </ul>
{% endblock %}